In [ ]:
#Mount to drive
#Easy access to files stored in your Google Drive
#Allowing you to read and write data directly from and to your Google Drive.
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Loading a training dataset in JSON format using the pandas library in Python.
file_path = r'/content/drive/My Drive/NLP/NLP_Project/complaints_filtered_trainData.csv'
train_data = pd.read_csv(file_path)
# Display the content of the dataset.
train_data

Unnamed: 0 Date received  \
0                0    2021-10-01   
1                1    2023-03-19   
2                2    2021-11-04   
3                3    2023-05-24   
4                4    2022-08-25   
...            ...           ...   
139995      139995    2021-12-21   
139996      139996    2023-01-19   
139997      139997    2022-03-17   
139998      139998    2023-07-06   
139999      139999    2022-02-11   

                                                narrative     product_category  
0       Attentively review my formal writ composed dec...      debt_collection  
1       XXXX XXXX, the resolution complaint specialist...       retail_banking  
2       Husband and I had our mortgage sold to 5/3 for...  mortgages_and_loans  
3       Complaint against XXXX XXXX XXXXXXXX. Claim nu...       retail_banking  
4       Paid off a loan for a travel trailer XX/XX/202...  mortgages_and_loans  
...                                                   ...                  ...  
139995  I already have a complaint that was filed with...  mortgages_and_loans  
139996  I rented a car from XXXX  rental car on XX/XX/...          credit_card  
139997  My credit report shows a collection from Midla...      debt_collection  
139998  Earlier this year, I purchased the following v...  mortgages_and_loans  
139999  I applied for the personal loan on XX/XX/2022 ...  mortgages_and_loans  

[140000 rows x 4 columns]

In [ ]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140000 entries, 0 to 139999
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   Unnamed: 0        140000 non-null  int64 
 1   Date received     140000 non-null  object
 2   narrative         140000 non-null  object
 3   product_category  140000 non-null  object
dtypes: int64(1), object(3)
memory usage: 4.3+ MB


In [ ]:
# Loading a testing dataset in JSON format using the pandas library in Python.
file_path = r'/content/drive/My Drive/NLP/NLP_Project/complaints_filtered_testData.csv'
test_data = pd.read_csv(file_path)
# Display the content of the dataset.
test_data

Unnamed: 0 Date received  \
0              0    2021-10-01   
1              1    2023-03-19   
2              2    2021-11-04   
3              3    2023-05-24   
4              4    2022-08-25   
...          ...           ...   
4995        4995    2023-02-06   
4996        4996    2023-08-02   
4997        4997    2023-04-13   
4998        4998    2021-12-31   
4999        4999    2022-01-25   

                                              narrative     product_category  
0     Attentively review my formal writ composed dec...      debt_collection  
1     XXXX XXXX, the resolution complaint specialist...       retail_banking  
2     Husband and I had our mortgage sold to 5/3 for...  mortgages_and_loans  
3     Complaint against XXXX XXXX XXXXXXXX. Claim nu...       retail_banking  
4     Paid off a loan for a travel trailer XX/XX/202...  mortgages_and_loans  
...                                                 ...                  ...  
4995  I transferred, XXXX USD from my bank account t...       retail_banking  
4996  In accordance with the Fair Credit Reporting A...     credit_reporting  
4997  On XX/XX/2023 I discovered and applied for a l...  mortgages_and_loans  
4998  On XX/XX/2021 I paid my co-pay of {$50.00} to ...      debt_collection  
4999  I applied to Amazon Commercial Credit Card iss...          credit_card  

[5000 rows x 4 columns]

In [ ]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Unnamed: 0        5000 non-null   int64 
 1   Date received     5000 non-null   object
 2   narrative         5000 non-null   object
 3   product_category  5000 non-null   object
dtypes: int64(1), object(3)
memory usage: 156.4+ KB


In [ ]:
#Remove the specified columns from the train dataset that are not relevant to the task.
columns_to_drop = ['Unnamed: 0']
train_data.drop(columns=columns_to_drop, inplace=True)
train_data.head()

Date received                                          narrative  \
0    2021-10-01  Attentively review my formal writ composed dec...   
1    2023-03-19  XXXX XXXX, the resolution complaint specialist...   
2    2021-11-04  Husband and I had our mortgage sold to 5/3 for...   
3    2023-05-24  Complaint against XXXX XXXX XXXXXXXX. Claim nu...   
4    2022-08-25  Paid off a loan for a travel trailer XX/XX/202...   

      product_category  
0      debt_collection  
1       retail_banking  
2  mortgages_and_loans  
3       retail_banking  
4  mortgages_and_loans

In [ ]:
#Remove the specified columns from the train dataset that are not relevant to the task.
columns_to_drop = ['Unnamed: 0']
test_data.drop(columns=columns_to_drop, inplace=True)
test_data.head()

Date received                                          narrative  \
0    2021-10-01  Attentively review my formal writ composed dec...   
1    2023-03-19  XXXX XXXX, the resolution complaint specialist...   
2    2021-11-04  Husband and I had our mortgage sold to 5/3 for...   
3    2023-05-24  Complaint against XXXX XXXX XXXXXXXX. Claim nu...   
4    2022-08-25  Paid off a loan for a travel trailer XX/XX/202...   

      product_category  
0      debt_collection  
1       retail_banking  
2  mortgages_and_loans  
3       retail_banking  
4  mortgages_and_loans

In [ ]:
type(np.array(train_data['narrative']))

numpy.ndarray

In [ ]:
train_data['product_category'].unique()

array(['debt_collection', 'retail_banking', 'mortgages_and_loans',
       'credit_card', 'credit_reporting'], dtype=object)

In [ ]:
product_dict ={'credit_reporting': 1, 'debt_collection': 2, 'mortgages_and_loans': 3,
               'credit_card': 0, 'retail_banking': 4}

In [ ]:
train_data['product_category'].replace(product_dict, inplace=True)

In [ ]:
train_data

Date received                                          narrative  \
0         2021-10-01  Attentively review my formal writ composed dec...   
1         2023-03-19  XXXX XXXX, the resolution complaint specialist...   
2         2021-11-04  Husband and I had our mortgage sold to 5/3 for...   
3         2023-05-24  Complaint against XXXX XXXX XXXXXXXX. Claim nu...   
4         2022-08-25  Paid off a loan for a travel trailer XX/XX/202...   
...              ...                                                ...   
139995    2021-12-21  I already have a complaint that was filed with...   
139996    2023-01-19  I rented a car from XXXX  rental car on XX/XX/...   
139997    2022-03-17  My credit report shows a collection from Midla...   
139998    2023-07-06  Earlier this year, I purchased the following v...   
139999    2022-02-11  I applied for the personal loan on XX/XX/2022 ...   

        product_category  
0                      2  
1                      4  
2                      3  
3                      4  
4                      3  
...                  ...  
139995                 3  
139996                 0  
139997                 2  
139998                 3  
139999                 3  

[140000 rows x 3 columns]

In [ ]:
test_data['product_category'].replace(product_dict, inplace=True)
test_data

Date received                                          narrative  \
0       2021-10-01  Attentively review my formal writ composed dec...   
1       2023-03-19  XXXX XXXX, the resolution complaint specialist...   
2       2021-11-04  Husband and I had our mortgage sold to 5/3 for...   
3       2023-05-24  Complaint against XXXX XXXX XXXXXXXX. Claim nu...   
4       2022-08-25  Paid off a loan for a travel trailer XX/XX/202...   
...            ...                                                ...   
4995    2023-02-06  I transferred, XXXX USD from my bank account t...   
4996    2023-08-02  In accordance with the Fair Credit Reporting A...   
4997    2023-04-13  On XX/XX/2023 I discovered and applied for a l...   
4998    2021-12-31  On XX/XX/2021 I paid my co-pay of {$50.00} to ...   
4999    2022-01-25  I applied to Amazon Commercial Credit Card iss...   

      product_category  
0                    2  
1                    4  
2                    3  
3                    4  
4                    3  
...                ...  
4995                 4  
4996                 1  
4997                 3  
4998                 2  
4999                 0  

[5000 rows x 3 columns]

In [ ]:
train_data['product_category'].unique()

array([2, 4, 3, 0, 1])

In [ ]:
train_data = train_data.dropna()

In [ ]:
test_data = test_data.dropna()

In [ ]:
Xtrain = train_data['narrative']
ytrain = train_data['product_category']

In [ ]:
Xtest = test_data['narrative']
ytest = test_data['product_category']

In [ ]:
Xtrain

0         Attentively review my formal writ composed dec...
1         XXXX XXXX, the resolution complaint specialist...
2         Husband and I had our mortgage sold to 5/3 for...
3         Complaint against XXXX XXXX XXXXXXXX. Claim nu...
4         Paid off a loan for a travel trailer XX/XX/202...
                                ...                        
139995    I already have a complaint that was filed with...
139996    I rented a car from XXXX  rental car on XX/XX/...
139997    My credit report shows a collection from Midla...
139998    Earlier this year, I purchased the following v...
139999    I applied for the personal loan on XX/XX/2022 ...
Name: narrative, Length: 140000, dtype: object

In [ ]:
ytrain

0         2
1         4
2         3
3         4
4         3
         ..
139995    3
139996    0
139997    2
139998    3
139999    3
Name: product_category, Length: 140000, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
# Used for splitting datasets into training and testing sets.
X_train, X_valid, y_train, y_valid = train_test_split(Xtrain, ytrain, test_size=0.20, random_state=200)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, recall_score
import matplotlib.pyplot as plt

#### Naive Bayes

In [ ]:
from sklearn.pipeline import make_pipeline
# Training the model
MNB_classifier = make_pipeline(TfidfVectorizer(), MultinomialNB())
MNB_classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('multinomialnb', MultinomialNB())])

In [ ]:
import joblib
joblib.dump(MNB_classifier, '/content/drive/My Drive/NLP/NLP_Project/naive_bayes_model.pth')

['/content/drive/My Drive/NLP/NLP_Project/naive_bayes_model.pth']

In [ ]:
#To make predictions on the validation set.
y_valid_pred = MNB_classifier.predict(X_valid)

In [ ]:
# calculate the accuracy of the classifier's predictions on the validation set.
y_valid_pred_accuracy = accuracy_score(y_valid, y_valid_pred)
y_valid_pred_accuracy

0.8122142857142857

In [ ]:
# Make predictions on the test set.
y_test_pred = MNB_classifier.predict(Xtest)

In [ ]:
# calculate the accuracy of the classifier's predictions on the test set.
y_test_pred_accuracy = accuracy_score(ytest, y_test_pred)
y_test_pred_accuracy

0.8382

In [ ]:
# classification report for the validation set
print(classification_report(y_valid, y_valid_pred))

              precision    recall  f1-score   support

           0       0.81      0.82      0.81      5624
           1       0.81      0.73      0.77      5502
           2       0.85      0.86      0.85      5602
           3       0.77      0.77      0.77      5601
           4       0.83      0.90      0.86      5671

    accuracy                           0.82     28000
   macro avg       0.82      0.82      0.81     28000
weighted avg       0.82      0.82      0.81     28000



In [ ]:
# confusion matrix for the validation set
print(confusion_matrix(y_valid, y_valid_pred))

[[4604  428  235  295   62]
 [ 643 4010  353  338  158]
 [ 172  259 4804  212  155]
 [ 235  190  159 4339  678]
 [  22   39   88  435 5087]]


In [ ]:
# classification report for the test set
print(classification_report(ytest, y_test_pred))

              precision    recall  f1-score   support

           0       0.82      0.83      0.83      1055
           1       0.83      0.76      0.79       976
           2       0.86      0.86      0.86       930
           3       0.82      0.82      0.82      1007
           4       0.85      0.92      0.88      1032

    accuracy                           0.84      5000
   macro avg       0.84      0.84      0.84      5000
weighted avg       0.84      0.84      0.84      5000



In [ ]:
# confusion matrix for the test set
print(confusion_matrix(ytest, y_test_pred))

[[880  80  47  41   7]
 [117 740  53  44  22]
 [ 27  41 799  29  34]
 [ 42  23  17 826  99]
 [  3   4  10  69 946]]


#### Random Forest

In [ ]:
from sklearn.pipeline import make_pipeline
# Training the model
rf_classifier = make_pipeline(TfidfVectorizer(), RandomForestClassifier(max_depth=20))
rf_classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('randomforestclassifier',
                 RandomForestClassifier(max_depth=20))])

In [ ]:
joblib.dump(rf_classifier, '/content/drive/My Drive/NLP/NLP_Project/random_forest_model.pth')

['/content/drive/My Drive/NLP/NLP_Project/random_forest_model.pth']

In [ ]:
#To make predictions on the validation set.
y_valid_pred = rf_classifier.predict(X_valid)

In [ ]:
# calculate the accuracy of the classifier's predictions on the validation set.
y_valid_pred_accuracy = accuracy_score(y_valid, y_valid_pred)
y_valid_pred_accuracy

0.8086428571428571

In [ ]:
# Make predictions on the test set.
y_test_pred = rf_classifier.predict(Xtest)

In [ ]:
# calculate the accuracy of the classifier's predictions on the test set.
y_test_pred_accuracy = accuracy_score(ytest, y_test_pred)
y_test_pred_accuracy

0.8554

In [ ]:
# classification report for the validation set
print(classification_report(y_valid, y_valid_pred))

              precision    recall  f1-score   support

           0       0.83      0.82      0.83      5624
           1       0.77      0.78      0.78      5502
           2       0.85      0.84      0.84      5602
           3       0.81      0.74      0.78      5601
           4       0.82      0.90      0.86      5671

    accuracy                           0.82     28000
   macro avg       0.82      0.82      0.82     28000
weighted avg       0.82      0.82      0.82     28000



In [ ]:
# confusion matrix for the validation set
print(confusion_matrix(y_valid, y_valid_pred))

[[4617  497  238  219   53]
 [ 506 4288  317  258  133]
 [ 174  359 4702  145  222]
 [ 225  270  198 4172  736]
 [  22  120   77  337 5115]]


In [ ]:
# classification report for the test set
print(classification_report(ytest, y_test_pred))

              precision    recall  f1-score   support

           0       0.86      0.85      0.85      1055
           1       0.80      0.82      0.81       976
           2       0.88      0.86      0.87       930
           3       0.87      0.82      0.84      1007
           4       0.87      0.93      0.90      1032

    accuracy                           0.86      5000
   macro avg       0.86      0.86      0.85      5000
weighted avg       0.86      0.86      0.86      5000



In [ ]:
# confusion matrix for the test set
print(confusion_matrix(ytest, y_test_pred))

[[894  84  36  36   5]
 [ 76 802  48  33  17]
 [ 28  51 801  16  34]
 [ 36  40  23 824  84]
 [  3  26   4  43 956]]


#### Decision Tree

In [ ]:
from sklearn.pipeline import make_pipeline
# Training the model
dtree_classifier = make_pipeline(TfidfVectorizer(), DecisionTreeClassifier(max_depth=20))
dtree_classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('decisiontreeclassifier',
                 DecisionTreeClassifier(max_depth=20))])

In [ ]:
joblib.dump(dtree_classifier, '/content/drive/My Drive/NLP/NLP_Project/decision_tree_model.pth')

In [ ]:
#To make predictions on the validation set.
y_valid_pred = dtree_classifier.predict(X_valid)

In [ ]:
# calculate the accuracy of the classifier's predictions on the validation set.
y_valid_pred_accuracy = accuracy_score(y_valid, y_valid_pred)
y_valid_pred_accuracy

0.754

In [ ]:
# Make predictions on the test set.
y_test_pred = dtree_classifier.predict(Xtest)

In [ ]:
# calculate the accuracy of the classifier's predictions on the test set.
y_test_pred_accuracy = accuracy_score(ytest, y_test_pred)
y_test_pred_accuracy

0.8546

In [ ]:
# classification report for the validation set
print(classification_report(y_valid, y_valid_pred))

              precision    recall  f1-score   support

           0       0.81      0.76      0.78      5624
           1       0.69      0.73      0.71      5502
           2       0.83      0.76      0.79      5602
           3       0.71      0.73      0.72      5601
           4       0.77      0.81      0.79      5671

    accuracy                           0.76     28000
   macro avg       0.76      0.76      0.76     28000
weighted avg       0.76      0.76      0.76     28000



In [ ]:
# confusion matrix for the validation set
print(confusion_matrix(y_valid, y_valid_pred))

[[4265  629  223  369  138]
 [ 520 4029  302  394  257]
 [ 233  508 4256  327  278]
 [ 224  411  169 4079  718]
 [  52  271  178  597 4573]]


In [ ]:
# classification report for the test set
print(classification_report(ytest, y_test_pred))

              precision    recall  f1-score   support

           0       0.88      0.84      0.86      1055
           1       0.78      0.82      0.80       976
           2       0.90      0.84      0.87       930
           3       0.81      0.82      0.81      1007
           4       0.84      0.88      0.86      1032

    accuracy                           0.84      5000
   macro avg       0.84      0.84      0.84      5000
weighted avg       0.84      0.84      0.84      5000



In [ ]:
# confusion matrix for the test set
print(confusion_matrix(ytest, y_test_pred))

[[882  84  23  50  16]
 [ 55 803  31  53  34]
 [ 30  52 779  41  28]
 [ 27  46  12 826  96]
 [  7  40  25  51 909]]
