In [1]:
!pip install --upgrade scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 19.8 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2


In [2]:
#Mount to drive
#Easy access to files stored in your Google Drive
#Allowing you to read and write data directly from and to your Google Drive.
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd
import numpy as np

In [4]:
# Loading a training dataset in JSON format using the pandas library in Python.
file_path = r'/content/drive/My Drive/NLP/NLP_Project/filtered_complaints_train_data.csv'
train_data = pd.read_csv(file_path)
# Display the content of the dataset.
train_data

Unnamed: 0 Date received  \
0               0    2019-04-23   
1               1    2023-03-31   
2               2    2022-12-10   
3               3    2021-01-29   
4               4    2018-08-14   
...           ...           ...   
49995       49995    2023-03-17   
49996       49996    2022-11-28   
49997       49997    2022-12-21   
49998       49998    2019-02-15   
49999       49999    2018-08-25   

                                               narrative     product_category  
0      saw debt report mine call portfolio recovery a...      debt_collection  
1      located ca contacted stating owed credit card ...      debt_collection  
2      got side track cause inflation went damaged fi...  mortgages_and_loans  
3      noticed derogatory account listed credit repor...      debt_collection  
4      went branch withdraw funds form certified chec...       retail_banking  
...                                                  ...                  ...  
49995  reinvestigated credit report realized informat...     credit_reporting  
49996  accordance fair credit reporting act convergen...     credit_reporting  
49997  cfpb write accordance fair credit reporting ac...     credit_reporting  
49998  would like see documents showing chain title l...      debt_collection  
49999  went purchase new vehicle connected one sales ...  mortgages_and_loans  

[50000 rows x 4 columns]

In [6]:
# Loading a testing dataset in JSON format using the pandas library in Python.
file_path = r'/content/drive/My Drive/NLP/NLP_Project/filtered_complaints_test_data.csv'
test_data = pd.read_csv(file_path)
# Display the content of the dataset.
test_data

Unnamed: 0 Date received  \
0              0    2018-01-15   
1              1    2020-11-01   
2              2    2022-04-16   
3              3    2015-07-14   
4              4    2020-03-18   
...          ...           ...   
4995        4995    2015-06-11   
4996        4996    2023-03-18   
4997        4997    2023-04-06   
4998        4998    2022-03-28   
4999        4999    2020-01-15   

                                              narrative     product_category  
0                     paypal stole money bank never got       retail_banking  
1     recently someone accessed bank account tried s...      debt_collection  
2     received letter employer wage garnishment star...      debt_collection  
3     macdowell assoc filed garnishment deft outdate...      debt_collection  
4     credence resource management llc texas receive...      debt_collection  
...                                                 ...                  ...  
4995  used servive store added bill used freezed acc...          credit_card  
4996  previous complaints matter addressed wells far...       retail_banking  
4997  western union customer since many years ago fr...       retail_banking  
4998  previous case closed somewhat resolved notifie...       retail_banking  
4999  logged onto pennymac site make mortgage paymen...  mortgages_and_loans  

[5000 rows x 4 columns]

In [7]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Unnamed: 0        50000 non-null  int64 
 1   Date received     50000 non-null  object
 2   narrative         49995 non-null  object
 3   product_category  50000 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.5+ MB


In [8]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Unnamed: 0        5000 non-null   int64 
 1   Date received     5000 non-null   object
 2   narrative         5000 non-null   object
 3   product_category  5000 non-null   object
dtypes: int64(1), object(3)
memory usage: 156.4+ KB


In [9]:
#Remove the specified columns from the train dataset that are not relevant to the task.
columns_to_drop = ['Unnamed: 0']
train_data.drop(columns=columns_to_drop, inplace=True)
train_data.head()

Date received                                          narrative  \
0    2019-04-23  saw debt report mine call portfolio recovery a...   
1    2023-03-31  located ca contacted stating owed credit card ...   
2    2022-12-10  got side track cause inflation went damaged fi...   
3    2021-01-29  noticed derogatory account listed credit repor...   
4    2018-08-14  went branch withdraw funds form certified chec...   

      product_category  
0      debt_collection  
1      debt_collection  
2  mortgages_and_loans  
3      debt_collection  
4       retail_banking

In [10]:
#Remove the specified columns from the train dataset that are not relevant to the task.
columns_to_drop = ['Unnamed: 0']
test_data.drop(columns=columns_to_drop, inplace=True)
test_data.head()

Date received                                          narrative  \
0    2018-01-15                  paypal stole money bank never got   
1    2020-11-01  recently someone accessed bank account tried s...   
2    2022-04-16  received letter employer wage garnishment star...   
3    2015-07-14  macdowell assoc filed garnishment deft outdate...   
4    2020-03-18  credence resource management llc texas receive...   

  product_category  
0   retail_banking  
1  debt_collection  
2  debt_collection  
3  debt_collection  
4  debt_collection

In [11]:
type(np.array(train_data['narrative']))

numpy.ndarray

In [12]:
train_data['product_category'].unique()

array(['debt_collection', 'mortgages_and_loans', 'retail_banking',
       'credit_card', 'credit_reporting'], dtype=object)

In [13]:
product_dict ={'credit_reporting': 1, 'debt_collection': 2, 'mortgages_and_loans': 3,
               'credit_card': 0, 'retail_banking': 4}

In [14]:
train_data['product_category'].replace(product_dict, inplace=True)

In [15]:
train_data

Date received                                          narrative  \
0        2019-04-23  saw debt report mine call portfolio recovery a...   
1        2023-03-31  located ca contacted stating owed credit card ...   
2        2022-12-10  got side track cause inflation went damaged fi...   
3        2021-01-29  noticed derogatory account listed credit repor...   
4        2018-08-14  went branch withdraw funds form certified chec...   
...             ...                                                ...   
49995    2023-03-17  reinvestigated credit report realized informat...   
49996    2022-11-28  accordance fair credit reporting act convergen...   
49997    2022-12-21  cfpb write accordance fair credit reporting ac...   
49998    2019-02-15  would like see documents showing chain title l...   
49999    2018-08-25  went purchase new vehicle connected one sales ...   

       product_category  
0                     2  
1                     2  
2                     3  
3                     2  
4                     4  
...                 ...  
49995                 1  
49996                 1  
49997                 1  
49998                 2  
49999                 3  

[50000 rows x 3 columns]

In [16]:
test_data['product_category'].replace(product_dict, inplace=True)
test_data

Date received                                          narrative  \
0       2018-01-15                  paypal stole money bank never got   
1       2020-11-01  recently someone accessed bank account tried s...   
2       2022-04-16  received letter employer wage garnishment star...   
3       2015-07-14  macdowell assoc filed garnishment deft outdate...   
4       2020-03-18  credence resource management llc texas receive...   
...            ...                                                ...   
4995    2015-06-11  used servive store added bill used freezed acc...   
4996    2023-03-18  previous complaints matter addressed wells far...   
4997    2023-04-06  western union customer since many years ago fr...   
4998    2022-03-28  previous case closed somewhat resolved notifie...   
4999    2020-01-15  logged onto pennymac site make mortgage paymen...   

      product_category  
0                    4  
1                    2  
2                    2  
3                    2  
4                    2  
...                ...  
4995                 0  
4996                 4  
4997                 4  
4998                 4  
4999                 3  

[5000 rows x 3 columns]

In [17]:
train_data['product_category'].unique()

array([2, 3, 4, 0, 1])

In [18]:
train_data = train_data.dropna()

In [19]:
test_data = test_data.dropna()

In [20]:
Xtrain = train_data['narrative']
ytrain = train_data['product_category']

In [21]:
Xtest = test_data['narrative']
ytest = test_data['product_category']

In [22]:
Xtrain

0        saw debt report mine call portfolio recovery a...
1        located ca contacted stating owed credit card ...
2        got side track cause inflation went damaged fi...
3        noticed derogatory account listed credit repor...
4        went branch withdraw funds form certified chec...
                               ...                        
49995    reinvestigated credit report realized informat...
49996    accordance fair credit reporting act convergen...
49997    cfpb write accordance fair credit reporting ac...
49998    would like see documents showing chain title l...
49999    went purchase new vehicle connected one sales ...
Name: narrative, Length: 49995, dtype: object

In [23]:
ytrain

0        2
1        2
2        3
3        2
4        4
        ..
49995    1
49996    1
49997    1
49998    2
49999    3
Name: product_category, Length: 49995, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split
# Used for splitting datasets into training and testing sets.
X_train, X_valid, y_train, y_valid = train_test_split(Xtrain, ytrain, test_size=0.20, random_state=200)

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, recall_score
import matplotlib.pyplot as plt

In [26]:
from sklearn.pipeline import make_pipeline
# Training the model
MNB_classifier = make_pipeline(TfidfVectorizer(), MultinomialNB())
MNB_classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('multinomialnb', MultinomialNB())])

In [27]:
#To make predictions on the validation set.
y_valid_pred = MNB_classifier.predict(X_valid)

In [28]:
# calculate the accuracy of the classifier's predictions on the validation set.
y_valid_pred_accuracy = accuracy_score(y_valid, y_valid_pred)
y_valid_pred_accuracy

0.8171817181718172

In [29]:
# Make predictions on the test set.
y_test_pred = MNB_classifier.predict(Xtest)

In [30]:
# calculate the accuracy of the classifier's predictions on the test set.
y_test_pred_accuracy = accuracy_score(ytest, y_test_pred)
y_test_pred_accuracy

0.8134

In [31]:
# classification report for the validation set
print(classification_report(y_valid, y_valid_pred))

              precision    recall  f1-score   support

           0       0.77      0.78      0.78      2027
           1       0.81      0.81      0.81      2040
           2       0.82      0.75      0.78      1922
           3       0.84      0.87      0.85      2006
           4       0.83      0.88      0.85      2004

    accuracy                           0.82      9999
   macro avg       0.82      0.82      0.82      9999
weighted avg       0.82      0.82      0.82      9999



In [32]:
# confusion matrix for the validation set
print(confusion_matrix(y_valid, y_valid_pred))

[[1581  107   59   50  230]
 [ 127 1660  141   90   22]
 [ 102  203 1435  143   39]
 [  63   58   86 1737   62]
 [ 170   19   19   38 1758]]


In [33]:
# classification report for the test set
print(classification_report(ytest, y_test_pred))

              precision    recall  f1-score   support

           0       0.77      0.78      0.78       979
           1       0.79      0.80      0.79      1006
           2       0.83      0.75      0.79      1020
           3       0.83      0.85      0.84       972
           4       0.84      0.88      0.86      1023

    accuracy                           0.81      5000
   macro avg       0.81      0.81      0.81      5000
weighted avg       0.81      0.81      0.81      5000



In [34]:
# confusion matrix for the test set
print(confusion_matrix(ytest, y_test_pred))

[[762  55  22  32 108]
 [ 59 809  74  54  10]
 [ 47 118 769  68  18]
 [ 27  39  47 827  32]
 [ 91   9   9  14 900]]


### Random Forest

In [35]:
from sklearn.pipeline import make_pipeline
# Training the model
rf_classifier = make_pipeline(TfidfVectorizer(), RandomForestClassifier(max_depth=20))
rf_classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('randomforestclassifier',
                 RandomForestClassifier(max_depth=20))])

In [36]:
#To make predictions on the validation set.
y_valid_pred = rf_classifier.predict(X_valid)

In [37]:
# calculate the accuracy of the classifier's predictions on the validation set.
y_valid_pred_accuracy = accuracy_score(y_valid, y_valid_pred)
y_valid_pred_accuracy

0.8068806880688069

In [38]:
# Make predictions on the test set.
y_test_pred = rf_classifier.predict(Xtest)

In [39]:
# calculate the accuracy of the classifier's predictions on the test set.
y_test_pred_accuracy = accuracy_score(ytest, y_test_pred)
y_test_pred_accuracy

0.7988

In [40]:
# classification report for the validation set
print(classification_report(y_valid, y_valid_pred))

              precision    recall  f1-score   support

           0       0.82      0.72      0.76      2027
           1       0.79      0.83      0.81      2040
           2       0.76      0.77      0.77      1922
           3       0.84      0.84      0.84      2006
           4       0.82      0.88      0.85      2004

    accuracy                           0.81      9999
   macro avg       0.81      0.81      0.81      9999
weighted avg       0.81      0.81      0.81      9999



In [41]:
# confusion matrix for the validation set
print(confusion_matrix(y_valid, y_valid_pred))

[[1455  127  114   69  262]
 [  79 1685  174   84   18]
 [  74  201 1482  129   36]
 [  47   83  120 1681   75]
 [ 124   24   51   40 1765]]


In [42]:
# classification report for the test set
print(classification_report(ytest, y_test_pred))

              precision    recall  f1-score   support

           0       0.81      0.72      0.76       979
           1       0.77      0.82      0.80      1006
           2       0.76      0.76      0.76      1020
           3       0.82      0.82      0.82       972
           4       0.83      0.87      0.85      1023

    accuracy                           0.80      5000
   macro avg       0.80      0.80      0.80      5000
weighted avg       0.80      0.80      0.80      5000



In [43]:
# confusion matrix for the test set
print(confusion_matrix(ytest, y_test_pred))

[[701  73  45  33 127]
 [ 29 826  92  51   8]
 [ 39 114 775  70  22]
 [ 31  37  75 799  30]
 [ 63  21  29  17 893]]


### Decision Tree

In [44]:
from sklearn.pipeline import make_pipeline
# Training the model
dtree_classifier = make_pipeline(TfidfVectorizer(), DecisionTreeClassifier(max_depth=20))
dtree_classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('decisiontreeclassifier',
                 DecisionTreeClassifier(max_depth=20))])

In [45]:
#To make predictions on the validation set.
y_valid_pred = dtree_classifier.predict(X_valid)

In [46]:
# calculate the accuracy of the classifier's predictions on the validation set.
y_valid_pred_accuracy = accuracy_score(y_valid, y_valid_pred)
y_valid_pred_accuracy

0.7221722172217222

In [47]:
# Make predictions on the test set.
y_test_pred = dtree_classifier.predict(Xtest)

In [48]:
# calculate the accuracy of the classifier's predictions on the test set.
y_test_pred_accuracy = accuracy_score(ytest, y_test_pred)
y_test_pred_accuracy

0.7258

In [49]:
# classification report for the validation set
print(classification_report(y_valid, y_valid_pred))

              precision    recall  f1-score   support

           0       0.67      0.69      0.68      2027
           1       0.75      0.71      0.73      2040
           2       0.64      0.72      0.68      1922
           3       0.80      0.75      0.77      2006
           4       0.75      0.75      0.75      2004

    accuracy                           0.72      9999
   macro avg       0.72      0.72      0.72      9999
weighted avg       0.73      0.72      0.72      9999



In [50]:
# confusion matrix for the validation set
print(confusion_matrix(y_valid, y_valid_pred))

[[1389  133  179   60  266]
 [ 168 1447  254  106   65]
 [ 148  192 1376  128   78]
 [  97  105  217 1501   86]
 [ 258   41  116   81 1508]]


In [51]:
# classification report for the test set
print(classification_report(ytest, y_test_pred))

              precision    recall  f1-score   support

           0       0.69      0.71      0.70       979
           1       0.75      0.73      0.74      1006
           2       0.66      0.69      0.68      1020
           3       0.77      0.73      0.75       972
           4       0.75      0.76      0.76      1023

    accuracy                           0.73      5000
   macro avg       0.73      0.73      0.73      5000
weighted avg       0.73      0.73      0.73      5000



In [52]:
# confusion matrix for the test set
print(confusion_matrix(ytest, y_test_pred))

[[695  64  74  32 114]
 [ 62 733 119  60  32]
 [ 83 105 707  76  49]
 [ 41  49 109 714  59]
 [120  22  61  40 780]]


### KNN

In [53]:
from sklearn.pipeline import make_pipeline
# Training the model
knn_classifier = make_pipeline(TfidfVectorizer(), KNeighborsClassifier(n_neighbors=5, weights='distance'))
knn_classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('kneighborsclassifier',
                 KNeighborsClassifier(weights='distance'))])

In [ ]:
import joblib
joblib.dump(knn_classifier, '/content/drive/My Drive/NLP/NLP_Project/KNN.pth')

['/content/drive/My Drive/NLP/NLP_Project/KNN.pth']

In [54]:
#To make predictions on the validation set.
y_valid_pred = knn_classifier.predict(X_valid)

In [55]:
# calculate the accuracy of the classifier's predictions on the validation set.
y_valid_pred_accuracy = accuracy_score(y_valid, y_valid_pred)
y_valid_pred_accuracy

0.7625762576257625

In [56]:
# Make predictions on the test set.
y_test_pred = knn_classifier.predict(Xtest)

In [57]:
# calculate the accuracy of the classifier's predictions on the test set.
y_test_pred_accuracy = accuracy_score(ytest, y_test_pred)
y_test_pred_accuracy

0.761

In [58]:
# classification report for the validation set
print(classification_report(y_valid, y_valid_pred))

              precision    recall  f1-score   support

           0       0.71      0.72      0.72      2027
           1       0.74      0.83      0.78      2040
           2       0.77      0.71      0.74      1922
           3       0.82      0.76      0.79      2006
           4       0.78      0.80      0.79      2004

    accuracy                           0.76      9999
   macro avg       0.76      0.76      0.76      9999
weighted avg       0.76      0.76      0.76      9999



In [59]:
# confusion matrix for the validation set
print(confusion_matrix(y_valid, y_valid_pred))

[[1461  149   78   79  260]
 [  97 1685  162   71   25]
 [ 113  271 1358  124   56]
 [ 148  100  126 1521  111]
 [ 240   58   40   66 1600]]


In [60]:
# classification report for the test set
print(classification_report(ytest, y_test_pred))

              precision    recall  f1-score   support

           0       0.70      0.70      0.70       979
           1       0.74      0.81      0.77      1006
           2       0.78      0.75      0.77      1020
           3       0.81      0.75      0.78       972
           4       0.78      0.79      0.79      1023

    accuracy                           0.76      5000
   macro avg       0.76      0.76      0.76      5000
weighted avg       0.76      0.76      0.76      5000



In [61]:
# confusion matrix for the test set
print(confusion_matrix(ytest, y_test_pred))

[[681  73  48  40 137]
 [ 57 813  83  39  14]
 [ 41 127 767  57  28]
 [ 68  52  65 731  56]
 [127  29  20  34 813]]


### Gredient Boost

In [62]:
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import GradientBoostingClassifier
# Training the model
gboost_classifier = make_pipeline(TfidfVectorizer(), GradientBoostingClassifier())
gboost_classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('gradientboostingclassifier', GradientBoostingClassifier())])

In [71]:
import joblib
joblib.dump(gboost_classifier, '/content/drive/My Drive/NLP/NLP_Project/gboost.pth')

['/content/drive/My Drive/NLP/NLP_Project/gboost.pth']

In [63]:
y_valid_pred = gboost_classifier.predict(X_valid)

In [64]:
# calculate the accuracy of the classifier's predictions on the validation set.
y_valid_pred_accuracy = accuracy_score(y_valid, y_valid_pred)
y_valid_pred_accuracy

0.8177817781778178

In [65]:
y_test_pred = gboost_classifier.predict(Xtest)

In [66]:
# calculate the accuracy of the classifier's predictions on the test set.
y_test_pred_accuracy = accuracy_score(ytest, y_test_pred)
y_test_pred_accuracy

0.8096

In [67]:
print(classification_report(y_valid, y_valid_pred))

              precision    recall  f1-score   support

           0       0.81      0.78      0.79      2027
           1       0.80      0.83      0.82      2040
           2       0.78      0.79      0.78      1922
           3       0.85      0.84      0.85      2006
           4       0.84      0.85      0.84      2004

    accuracy                           0.82      9999
   macro avg       0.82      0.82      0.82      9999
weighted avg       0.82      0.82      0.82      9999



In [68]:
print(confusion_matrix(y_valid, y_valid_pred))

[[1572  120   99   38  198]
 [  83 1685  157   90   25]
 [  60  179 1514  120   49]
 [  44   85  118 1693   66]
 [ 170   25   50   46 1713]]


In [69]:
print(classification_report(ytest, y_test_pred))

              precision    recall  f1-score   support

           0       0.81      0.77      0.79       979
           1       0.79      0.82      0.80      1006
           2       0.77      0.76      0.77      1020
           3       0.83      0.83      0.83       972
           4       0.85      0.87      0.86      1023

    accuracy                           0.81      5000
   macro avg       0.81      0.81      0.81      5000
weighted avg       0.81      0.81      0.81      5000



In [70]:
print(confusion_matrix(ytest, y_test_pred))

[[758  59  45  24  93]
 [ 34 820  90  53   9]
 [ 48 108 777  66  21]
 [ 14  39  75 804  40]
 [ 80  12  21  21 889]]


### XGBoost

In [72]:
from xgboost import XGBClassifier
from sklearn.pipeline import make_pipeline
# Training the model
xgboost_classifier = make_pipeline(TfidfVectorizer(), XGBClassifier())
xgboost_classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('xgbclassifier',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None,
                               objective='multi:softprob', ...))])

In [81]:
import joblib
joblib.dump(xgboost_classifier, '/content/drive/My Drive/NLP/NLP_Project/xgboost.pth')

['/content/drive/My Drive/NLP/NLP_Project/xgboost.pth']

In [73]:
y_valid_pred = xgboost_classifier.predict(X_valid)

In [74]:
# calculate the accuracy of the classifier's predictions on the validation set.
y_valid_pred_accuracy = accuracy_score(y_valid, y_valid_pred)
y_valid_pred_accuracy

0.8355835583558355

In [75]:
y_test_pred = xgboost_classifier.predict(Xtest)

In [76]:
# calculate the accuracy of the classifier's predictions on the test set.
y_test_pred_accuracy = accuracy_score(ytest, y_test_pred)
y_test_pred_accuracy

0.8296

In [77]:
print(classification_report(y_valid, y_valid_pred))

              precision    recall  f1-score   support

           0       0.83      0.80      0.81      2027
           1       0.82      0.84      0.83      2040
           2       0.80      0.80      0.80      1922
           3       0.87      0.86      0.86      2006
           4       0.86      0.87      0.87      2004

    accuracy                           0.84      9999
   macro avg       0.84      0.84      0.84      9999
weighted avg       0.84      0.84      0.84      9999



In [78]:
print(confusion_matrix(y_valid, y_valid_pred))

[[1618  105   86   37  181]
 [  74 1718  149   83   16]
 [  66  169 1543  107   37]
 [  43   73  110 1725   55]
 [ 147   24   40   42 1751]]


In [79]:
print(classification_report(ytest, y_test_pred))

              precision    recall  f1-score   support

           0       0.82      0.81      0.81       979
           1       0.82      0.82      0.82      1006
           2       0.79      0.79      0.79      1020
           3       0.85      0.84      0.84       972
           4       0.87      0.88      0.88      1023

    accuracy                           0.83      5000
   macro avg       0.83      0.83      0.83      5000
weighted avg       0.83      0.83      0.83      5000



In [80]:
print(confusion_matrix(ytest, y_test_pred))

[[794  45  40  18  82]
 [ 39 827  85  49   6]
 [ 45  85 809  62  19]
 [ 21  40  67 818  26]
 [ 74   7  22  20 900]]
