In [1]:
!pip install --upgrade scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 55.0 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2


In [2]:
#Mount to drive
#Easy access to files stored in your Google Drive
#Allowing you to read and write data directly from and to your Google Drive.
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd
import numpy as np
import joblib

In [4]:
# Loading a training dataset in JSON format using the pandas library in Python.
file_path = r'/content/drive/My Drive/NLP/NLP_Project/complaints_preprocessed_and_balanced_400000_train_data.csv'
train_data = pd.read_csv(file_path)
# Display the content of the dataset.
train_data

Unnamed: 0.1  Unnamed: 0 Date received  \
0                  0       39898    2023-04-20   
1                  1      291821    2020-03-10   
2                  2      566561    2023-03-03   
3                  3      377432    2018-04-21   
4                  4       30960    2021-03-25   
...              ...         ...           ...   
399995        399995      351660    2023-06-22   
399996        399996      380158    2021-08-23   
399997        399997      223038    2017-01-11   
399998        399998      132984    2015-05-11   
399999        399999      283806    2022-04-06   

                                                narrative     product_category  
0       reference dispute case number amount unlawfull...          credit_card  
1       coinbases transfer fraud scam brokers would li...       retail_banking  
2       found cards ca used ca check balance called cu...          credit_card  
3       ran social security number bankruptcy database...     credit_reporting  
4       citibank twice determined responsible fraudule...          credit_card  
...                                                   ...                  ...  
399995  filed va partial claim know mortgage company i...  mortgages_and_loans  
399996  received notice amount hospital never sent bil...      debt_collection  
399997  receive subpoena debt days prior trial unable ...      debt_collection  
399998  phoned malicious virus computer charged dollar...       retail_banking  
399999  washington federal push us applied loan approv...  mortgages_and_loans  

[400000 rows x 5 columns]

In [5]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   Unnamed: 0.1      400000 non-null  int64 
 1   Unnamed: 0        400000 non-null  int64 
 2   Date received     400000 non-null  object
 3   narrative         399999 non-null  object
 4   product_category  400000 non-null  object
dtypes: int64(2), object(3)
memory usage: 15.3+ MB


In [6]:
# Loading a testing dataset in JSON format using the pandas library in Python.
file_path = r'/content/drive/My Drive/NLP/NLP_Project/complaints_preprocessed_and_balanced_10000_test_data.csv'
test_data = pd.read_csv(file_path)
# Display the content of the dataset.
test_data

Unnamed: 0.1  Unnamed: 0 Date received  \
0                0      471559    2022-11-13   
1                1      296939    2023-01-30   
2                2       94115    2018-09-04   
3                3      515522    2023-06-28   
4                4      382003    2019-02-13   
...            ...         ...           ...   
9995          9995      125121    2018-09-16   
9996          9996      344685    2023-06-28   
9997          9997       98051    2020-10-01   
9998          9998      381035    2019-01-07   
9999          9999      561240    2020-01-09   

                                              narrative     product_category  
0     around applied home equity loan navy federal c...  mortgages_and_loans  
1     mohela may concern agree pay following financi...  mortgages_and_loans  
2     diversified consultants trying go debt mine fe...      debt_collection  
3     purchased night stay checked room midnight dis...          credit_card  
4     works money burn order pay bills decided sell ...       retail_banking  
...                                                 ...                  ...  
9995  contracted install new heating cooling system ...      debt_collection  
9996  reviewed credit report discovered information ...     credit_reporting  
9997  may concern facing reduced work hours due reac...          credit_card  
9998  transactions withdrawn account using contacted...       retail_banking  
9999  surge card continental finance usual made mini...     credit_reporting  

[10000 rows x 5 columns]

In [7]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Unnamed: 0.1      10000 non-null  int64 
 1   Unnamed: 0        10000 non-null  int64 
 2   Date received     10000 non-null  object
 3   narrative         10000 non-null  object
 4   product_category  10000 non-null  object
dtypes: int64(2), object(3)
memory usage: 390.8+ KB


In [8]:
#Remove the specified columns from the train dataset that are not relevant to the task.
columns_to_drop = ['Unnamed: 0']
train_data.drop(columns=columns_to_drop, inplace=True)
train_data.head()

Unnamed: 0.1 Date received  \
0             0    2023-04-20   
1             1    2020-03-10   
2             2    2023-03-03   
3             3    2018-04-21   
4             4    2021-03-25   

                                           narrative  product_category  
0  reference dispute case number amount unlawfull...       credit_card  
1  coinbases transfer fraud scam brokers would li...    retail_banking  
2  found cards ca used ca check balance called cu...       credit_card  
3  ran social security number bankruptcy database...  credit_reporting  
4  citibank twice determined responsible fraudule...       credit_card

In [9]:
#Remove the specified columns from the train dataset that are not relevant to the task.
columns_to_drop = ['Unnamed: 0']
test_data.drop(columns=columns_to_drop, inplace=True)
test_data.head()

Unnamed: 0.1 Date received  \
0             0    2022-11-13   
1             1    2023-01-30   
2             2    2018-09-04   
3             3    2023-06-28   
4             4    2019-02-13   

                                           narrative     product_category  
0  around applied home equity loan navy federal c...  mortgages_and_loans  
1  mohela may concern agree pay following financi...  mortgages_and_loans  
2  diversified consultants trying go debt mine fe...      debt_collection  
3  purchased night stay checked room midnight dis...          credit_card  
4  works money burn order pay bills decided sell ...       retail_banking

In [10]:
type(np.array(train_data['narrative']))

numpy.ndarray

In [11]:
train_data['product_category'].unique()

array(['credit_card', 'retail_banking', 'credit_reporting',
       'mortgages_and_loans', 'debt_collection'], dtype=object)

In [12]:
product_dict ={'credit_reporting': 1, 'debt_collection': 2, 'mortgages_and_loans': 3,
               'credit_card': 0, 'retail_banking': 4}

In [13]:
train_data['product_category'].replace(product_dict, inplace=True)

In [14]:
train_data

Unnamed: 0.1 Date received  \
0                  0    2023-04-20   
1                  1    2020-03-10   
2                  2    2023-03-03   
3                  3    2018-04-21   
4                  4    2021-03-25   
...              ...           ...   
399995        399995    2023-06-22   
399996        399996    2021-08-23   
399997        399997    2017-01-11   
399998        399998    2015-05-11   
399999        399999    2022-04-06   

                                                narrative  product_category  
0       reference dispute case number amount unlawfull...                 0  
1       coinbases transfer fraud scam brokers would li...                 4  
2       found cards ca used ca check balance called cu...                 0  
3       ran social security number bankruptcy database...                 1  
4       citibank twice determined responsible fraudule...                 0  
...                                                   ...               ...  
399995  filed va partial claim know mortgage company i...                 3  
399996  received notice amount hospital never sent bil...                 2  
399997  receive subpoena debt days prior trial unable ...                 2  
399998  phoned malicious virus computer charged dollar...                 4  
399999  washington federal push us applied loan approv...                 3  

[400000 rows x 4 columns]

In [15]:
test_data['product_category'].replace(product_dict, inplace=True)
test_data

Unnamed: 0.1 Date received  \
0                0    2022-11-13   
1                1    2023-01-30   
2                2    2018-09-04   
3                3    2023-06-28   
4                4    2019-02-13   
...            ...           ...   
9995          9995    2018-09-16   
9996          9996    2023-06-28   
9997          9997    2020-10-01   
9998          9998    2019-01-07   
9999          9999    2020-01-09   

                                              narrative  product_category  
0     around applied home equity loan navy federal c...                 3  
1     mohela may concern agree pay following financi...                 3  
2     diversified consultants trying go debt mine fe...                 2  
3     purchased night stay checked room midnight dis...                 0  
4     works money burn order pay bills decided sell ...                 4  
...                                                 ...               ...  
9995  contracted install new heating cooling system ...                 2  
9996  reviewed credit report discovered information ...                 1  
9997  may concern facing reduced work hours due reac...                 0  
9998  transactions withdrawn account using contacted...                 4  
9999  surge card continental finance usual made mini...                 1  

[10000 rows x 4 columns]

In [16]:
train_data['product_category'].unique()

array([0, 4, 1, 3, 2])

In [17]:
train_data = train_data.dropna()

In [18]:
test_data = test_data.dropna()

In [19]:
Xtrain = train_data['narrative']
ytrain = train_data['product_category']

In [20]:
Xtest = test_data['narrative']
ytest = test_data['product_category']

In [21]:
Xtrain

0         reference dispute case number amount unlawfull...
1         coinbases transfer fraud scam brokers would li...
2         found cards ca used ca check balance called cu...
3         ran social security number bankruptcy database...
4         citibank twice determined responsible fraudule...
                                ...                        
399995    filed va partial claim know mortgage company i...
399996    received notice amount hospital never sent bil...
399997    receive subpoena debt days prior trial unable ...
399998    phoned malicious virus computer charged dollar...
399999    washington federal push us applied loan approv...
Name: narrative, Length: 399999, dtype: object

In [22]:
ytrain

0         0
1         4
2         0
3         1
4         0
         ..
399995    3
399996    2
399997    2
399998    4
399999    3
Name: product_category, Length: 399999, dtype: int64

In [23]:
from sklearn.model_selection import train_test_split
# Used for splitting datasets into training and testing sets.
X_train, X_valid, y_train, y_valid = train_test_split(Xtrain, ytrain, test_size=0.20, random_state=200)

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, recall_score
import matplotlib.pyplot as plt

#### Naive Bayes

In [25]:
from sklearn.pipeline import make_pipeline
# Training the model
MNB_classifier = make_pipeline(TfidfVectorizer(), MultinomialNB())
MNB_classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('multinomialnb', MultinomialNB())])

In [26]:
#To make predictions on the validation set.
y_valid_pred = MNB_classifier.predict(X_valid)

In [27]:
# calculate the accuracy of the classifier's predictions on the validation set.
y_valid_pred_accuracy = accuracy_score(y_valid, y_valid_pred)
y_valid_pred_accuracy

0.823

In [28]:
# Make predictions on the test set.
y_test_pred = MNB_classifier.predict(Xtest)

In [29]:
# calculate the accuracy of the classifier's predictions on the test set.
y_test_pred_accuracy = accuracy_score(ytest, y_test_pred)
y_test_pred_accuracy

0.8233

In [30]:
# classification report for the validation set
print(classification_report(y_valid, y_valid_pred))

              precision    recall  f1-score   support

           0       0.79      0.79      0.79     16252
           1       0.81      0.78      0.79     15071
           2       0.84      0.77      0.80     16100
           3       0.84      0.88      0.86     16138
           4       0.84      0.89      0.86     16439

    accuracy                           0.82     80000
   macro avg       0.82      0.82      0.82     80000
weighted avg       0.82      0.82      0.82     80000



In [31]:
# confusion matrix for the validation set
print(confusion_matrix(y_valid, y_valid_pred))

[[12872   650   428   390  1912]
 [  971 11735  1237   928   200]
 [  719  1541 12413  1133   294]
 [  525   444   592 14154   423]
 [ 1180   117   153   323 14666]]


In [32]:
# classification report for the test set
print(classification_report(ytest, y_test_pred))

              precision    recall  f1-score   support

           0       0.78      0.79      0.79      2019
           1       0.82      0.77      0.80      1873
           2       0.84      0.77      0.80      2086
           3       0.84      0.89      0.86      1997
           4       0.83      0.89      0.86      2025

    accuracy                           0.82     10000
   macro avg       0.82      0.82      0.82     10000
weighted avg       0.82      0.82      0.82     10000



In [33]:
# confusion matrix for the test set
print(confusion_matrix(ytest, y_test_pred))

[[1590   73   53   49  254]
 [ 114 1440  182  119   18]
 [ 114  177 1614  143   38]
 [  65   44   61 1777   50]
 [ 147   12   16   38 1812]]


In [34]:
joblib.dump(MNB_classifier, '/content/drive/My Drive/NLP/NLP_Project/naive_bayes_model.pth')

['/content/drive/My Drive/NLP/NLP_Project/naive_bayes_model.pth']

#### Random Forest

In [35]:
from sklearn.pipeline import make_pipeline
# Training the model
rf_classifier = make_pipeline(TfidfVectorizer(), RandomForestClassifier(max_depth=20))
rf_classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('randomforestclassifier',
                 RandomForestClassifier(max_depth=20))])

In [36]:
#To make predictions on the validation set.
y_valid_pred = rf_classifier.predict(X_valid)

In [37]:
# calculate the accuracy of the classifier's predictions on the validation set.
y_valid_pred_accuracy = accuracy_score(y_valid, y_valid_pred)
y_valid_pred_accuracy

0.8039875

In [38]:
# Make predictions on the test set.
y_test_pred = rf_classifier.predict(Xtest)

In [39]:
# calculate the accuracy of the classifier's predictions on the test set.
y_test_pred_accuracy = accuracy_score(ytest, y_test_pred)
y_test_pred_accuracy

0.8074

In [40]:
# classification report for the validation set
print(classification_report(y_valid, y_valid_pred))

              precision    recall  f1-score   support

           0       0.83      0.71      0.77     16252
           1       0.79      0.78      0.79     15071
           2       0.76      0.78      0.77     16100
           3       0.84      0.84      0.84     16138
           4       0.80      0.90      0.85     16439

    accuracy                           0.80     80000
   macro avg       0.80      0.80      0.80     80000
weighted avg       0.81      0.80      0.80     80000



In [41]:
# confusion matrix for the validation set
print(confusion_matrix(y_valid, y_valid_pred))

[[11612   857   886   496  2401]
 [  632 11775  1708   796   160]
 [  528  1492 12591  1100   389]
 [  349   586   966 13594   643]
 [  791   173   438   290 14747]]


In [42]:
# classification report for the test set
print(classification_report(ytest, y_test_pred))

              precision    recall  f1-score   support

           0       0.84      0.70      0.76      2019
           1       0.81      0.78      0.79      1873
           2       0.77      0.79      0.78      2086
           3       0.83      0.86      0.84      1997
           4       0.80      0.91      0.85      2025

    accuracy                           0.81     10000
   macro avg       0.81      0.81      0.81     10000
weighted avg       0.81      0.81      0.81     10000



In [43]:
# confusion matrix for the test set
print(confusion_matrix(ytest, y_test_pred))

[[1421   97  109   64  328]
 [  77 1457  211  108   20]
 [  82  168 1641  145   50]
 [  33   61  117 1712   74]
 [  86   13   54   29 1843]]


In [44]:
joblib.dump(rf_classifier, '/content/drive/My Drive/NLP/NLP_Project/random_forest_model.pth')

['/content/drive/My Drive/NLP/NLP_Project/random_forest_model.pth']

#### Decision Tree

In [45]:
from sklearn.pipeline import make_pipeline
# Training the model
dtree_classifier = make_pipeline(TfidfVectorizer(), DecisionTreeClassifier(max_depth=20))
dtree_classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('decisiontreeclassifier',
                 DecisionTreeClassifier(max_depth=20))])

In [46]:
#To make predictions on the validation set.
y_valid_pred = dtree_classifier.predict(X_valid)

In [47]:
# calculate the accuracy of the classifier's predictions on the validation set.
y_valid_pred_accuracy = accuracy_score(y_valid, y_valid_pred)
y_valid_pred_accuracy

0.7578625

In [48]:
# Make predictions on the test set.
y_test_pred = dtree_classifier.predict(Xtest)

In [49]:
# calculate the accuracy of the classifier's predictions on the test set.
y_test_pred_accuracy = accuracy_score(ytest, y_test_pred)
y_test_pred_accuracy

0.7641

In [50]:
# classification report for the validation set
print(classification_report(y_valid, y_valid_pred))

              precision    recall  f1-score   support

           0       0.72      0.74      0.73     16252
           1       0.80      0.72      0.76     15071
           2       0.69      0.75      0.72     16100
           3       0.82      0.78      0.80     16138
           4       0.78      0.80      0.79     16439

    accuracy                           0.76     80000
   macro avg       0.76      0.76      0.76     80000
weighted avg       0.76      0.76      0.76     80000



In [51]:
# confusion matrix for the validation set
print(confusion_matrix(y_valid, y_valid_pred))

[[12098   644  1301   386  1823]
 [ 1171 10851  1787   845   417]
 [ 1125  1255 12010   950   760]
 [  803   688  1387 12515   745]
 [ 1681   181   883   539 13155]]


In [52]:
# classification report for the test set
print(classification_report(ytest, y_test_pred))

              precision    recall  f1-score   support

           0       0.74      0.76      0.75      2019
           1       0.80      0.71      0.75      1873
           2       0.70      0.74      0.72      2086
           3       0.82      0.79      0.81      1997
           4       0.78      0.82      0.80      2025

    accuracy                           0.76     10000
   macro avg       0.77      0.76      0.76     10000
weighted avg       0.77      0.76      0.76     10000



In [53]:
# confusion matrix for the test set
print(confusion_matrix(ytest, y_test_pred))

[[1529   74  145   32  239]
 [ 149 1327  249  100   48]
 [ 143  162 1546  140   95]
 [  78   76  164 1582   97]
 [ 177   10  114   67 1657]]


In [54]:
joblib.dump(dtree_classifier, '/content/drive/My Drive/NLP/NLP_Project/decision_tree_model.pth')

['/content/drive/My Drive/NLP/NLP_Project/decision_tree_model.pth']