In [ ]:
#Mount to drive
#Easy access to files stored in your Google Drive
#Allowing you to read and write data directly from and to your Google Drive.
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Loading a training dataset in JSON format using the pandas library in Python.
file_path = r'/content/drive/My Drive/NLP/NLP_Project/complaints_preprocessed_and_balanced_200000_train_data.csv'
train_data = pd.read_csv(file_path)
# Display the content of the dataset.
train_data

Unnamed: 0.1  Unnamed: 0 Date received  \
0                  0       39898    2023-04-20   
1                  1      291821    2020-03-10   
2                  2      566561    2023-03-03   
3                  3      377432    2018-04-21   
4                  4       30960    2021-03-25   
...              ...         ...           ...   
199995        199995      607872    2019-05-03   
199996        199996      438531    2021-07-21   
199997        199997      405422    2017-10-17   
199998        199998      152541    2023-05-30   
199999        199999      348354    2021-05-14   

                                                narrative     product_category  
0       reference dispute case number amount unlawfull...          credit_card  
1       coinbases transfer fraud scam brokers would li...       retail_banking  
2       found cards ca used ca check balance called cu...          credit_card  
3       ran social security number bankruptcy database...     credit_reporting  
4       citibank twice determined responsible fraudule...          credit_card  
...                                                   ...                  ...  
199995  accessed bluebird american express account sin...          credit_card  
199996  got email owe speedy cash money havent even ta...      debt_collection  
199997  student loan lender multiple duplication accou...  mortgages_and_loans  
199998  issues enrolling online banking requested rsa ...       retail_banking  
199999  asked chime cut card head allowed chime receiv...       retail_banking  

[200000 rows x 5 columns]

In [ ]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   Unnamed: 0.1      200000 non-null  int64 
 1   Unnamed: 0        200000 non-null  int64 
 2   Date received     200000 non-null  object
 3   narrative         199999 non-null  object
 4   product_category  200000 non-null  object
dtypes: int64(2), object(3)
memory usage: 7.6+ MB


In [ ]:
# Loading a testing dataset in JSON format using the pandas library in Python.
file_path = r'/content/drive/My Drive/NLP/NLP_Project/complaints_preprocessed_and_balanced_10000_test_data.csv'
test_data = pd.read_csv(file_path)
# Display the content of the dataset.
test_data

Unnamed: 0.1  Unnamed: 0 Date received  \
0                0      471559    2022-11-13   
1                1      296939    2023-01-30   
2                2       94115    2018-09-04   
3                3      515522    2023-06-28   
4                4      382003    2019-02-13   
...            ...         ...           ...   
9995          9995      125121    2018-09-16   
9996          9996      344685    2023-06-28   
9997          9997       98051    2020-10-01   
9998          9998      381035    2019-01-07   
9999          9999      561240    2020-01-09   

                                              narrative     product_category  
0     around applied home equity loan navy federal c...  mortgages_and_loans  
1     mohela may concern agree pay following financi...  mortgages_and_loans  
2     diversified consultants trying go debt mine fe...      debt_collection  
3     purchased night stay checked room midnight dis...          credit_card  
4     works money burn order pay bills decided sell ...       retail_banking  
...                                                 ...                  ...  
9995  contracted install new heating cooling system ...      debt_collection  
9996  reviewed credit report discovered information ...     credit_reporting  
9997  may concern facing reduced work hours due reac...          credit_card  
9998  transactions withdrawn account using contacted...       retail_banking  
9999  surge card continental finance usual made mini...     credit_reporting  

[10000 rows x 5 columns]

In [ ]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Unnamed: 0.1      10000 non-null  int64 
 1   Unnamed: 0        10000 non-null  int64 
 2   Date received     10000 non-null  object
 3   narrative         10000 non-null  object
 4   product_category  10000 non-null  object
dtypes: int64(2), object(3)
memory usage: 390.8+ KB


In [ ]:
#Remove the specified columns from the train dataset that are not relevant to the task.
columns_to_drop = ['Unnamed: 0']
train_data.drop(columns=columns_to_drop, inplace=True)
train_data.head()

Unnamed: 0.1 Date received  \
0             0    2023-04-20   
1             1    2020-03-10   
2             2    2023-03-03   
3             3    2018-04-21   
4             4    2021-03-25   

                                           narrative  product_category  
0  reference dispute case number amount unlawfull...       credit_card  
1  coinbases transfer fraud scam brokers would li...    retail_banking  
2  found cards ca used ca check balance called cu...       credit_card  
3  ran social security number bankruptcy database...  credit_reporting  
4  citibank twice determined responsible fraudule...       credit_card

In [ ]:
#Remove the specified columns from the train dataset that are not relevant to the task.
columns_to_drop = ['Unnamed: 0']
test_data.drop(columns=columns_to_drop, inplace=True)
test_data.head()

Unnamed: 0.1 Date received  \
0             0    2022-11-13   
1             1    2023-01-30   
2             2    2018-09-04   
3             3    2023-06-28   
4             4    2019-02-13   

                                           narrative     product_category  
0  around applied home equity loan navy federal c...  mortgages_and_loans  
1  mohela may concern agree pay following financi...  mortgages_and_loans  
2  diversified consultants trying go debt mine fe...      debt_collection  
3  purchased night stay checked room midnight dis...          credit_card  
4  works money burn order pay bills decided sell ...       retail_banking

In [ ]:
type(np.array(train_data['narrative']))

numpy.ndarray

In [ ]:
train_data['product_category'].unique()

array(['credit_card', 'retail_banking', 'credit_reporting',
       'mortgages_and_loans', 'debt_collection'], dtype=object)

In [ ]:
product_dict ={'credit_reporting': 0, 'debt_collection': 1, 'mortgages_and_loans': 2,
               'credit_card': 3, 'retail_banking': 4}

In [ ]:
train_data['product_category'].replace(product_dict, inplace=True)

In [ ]:
train_data

Unnamed: 0.1 Date received  \
0                  0    2023-04-20   
1                  1    2020-03-10   
2                  2    2023-03-03   
3                  3    2018-04-21   
4                  4    2021-03-25   
...              ...           ...   
199995        199995    2019-05-03   
199996        199996    2021-07-21   
199997        199997    2017-10-17   
199998        199998    2023-05-30   
199999        199999    2021-05-14   

                                                narrative  product_category  
0       reference dispute case number amount unlawfull...                 3  
1       coinbases transfer fraud scam brokers would li...                 4  
2       found cards ca used ca check balance called cu...                 3  
3       ran social security number bankruptcy database...                 0  
4       citibank twice determined responsible fraudule...                 3  
...                                                   ...               ...  
199995  accessed bluebird american express account sin...                 3  
199996  got email owe speedy cash money havent even ta...                 1  
199997  student loan lender multiple duplication accou...                 2  
199998  issues enrolling online banking requested rsa ...                 4  
199999  asked chime cut card head allowed chime receiv...                 4  

[200000 rows x 4 columns]

In [ ]:
test_data['product_category'].replace(product_dict, inplace=True)
test_data

Unnamed: 0.1 Date received  \
0                0    2022-11-13   
1                1    2023-01-30   
2                2    2018-09-04   
3                3    2023-06-28   
4                4    2019-02-13   
...            ...           ...   
9995          9995    2018-09-16   
9996          9996    2023-06-28   
9997          9997    2020-10-01   
9998          9998    2019-01-07   
9999          9999    2020-01-09   

                                              narrative  product_category  
0     around applied home equity loan navy federal c...                 2  
1     mohela may concern agree pay following financi...                 2  
2     diversified consultants trying go debt mine fe...                 1  
3     purchased night stay checked room midnight dis...                 3  
4     works money burn order pay bills decided sell ...                 4  
...                                                 ...               ...  
9995  contracted install new heating cooling system ...                 1  
9996  reviewed credit report discovered information ...                 0  
9997  may concern facing reduced work hours due reac...                 3  
9998  transactions withdrawn account using contacted...                 4  
9999  surge card continental finance usual made mini...                 0  

[10000 rows x 4 columns]

In [ ]:
train_data['product_category'].unique()

array([3, 4, 0, 2, 1])

In [ ]:
train_data = train_data.dropna()

In [ ]:
test_data = test_data.dropna()

In [ ]:
Xtrain = train_data['narrative']
ytrain = train_data['product_category']

In [ ]:
Xtest = test_data['narrative']
ytest = test_data['product_category']

In [ ]:
Xtrain

0         reference dispute case number amount unlawfull...
1         coinbases transfer fraud scam brokers would li...
2         found cards ca used ca check balance called cu...
3         ran social security number bankruptcy database...
4         citibank twice determined responsible fraudule...
                                ...                        
199995    accessed bluebird american express account sin...
199996    got email owe speedy cash money havent even ta...
199997    student loan lender multiple duplication accou...
199998    issues enrolling online banking requested rsa ...
199999    asked chime cut card head allowed chime receiv...
Name: narrative, Length: 199999, dtype: object

In [ ]:
ytrain

0         3
1         4
2         3
3         0
4         3
         ..
199995    3
199996    1
199997    2
199998    4
199999    4
Name: product_category, Length: 199999, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
# Used for splitting datasets into training and testing sets.
X_train, X_valid, y_train, y_valid = train_test_split(Xtrain, ytrain, test_size=0.20, random_state=200)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, recall_score
import matplotlib.pyplot as plt

#### Naive Bayes

In [ ]:
from sklearn.pipeline import make_pipeline
# Training the model
MNB_classifier = make_pipeline(TfidfVectorizer(), MultinomialNB())
MNB_classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('multinomialnb', MultinomialNB())])

In [ ]:
#To make predictions on the validation set.
y_valid_pred = MNB_classifier.predict(X_valid)

In [ ]:
# calculate the accuracy of the classifier's predictions on the validation set.
y_valid_pred_accuracy = accuracy_score(y_valid, y_valid_pred)
y_valid_pred_accuracy

0.82085

In [ ]:
# Make predictions on the test set.
y_test_pred = MNB_classifier.predict(Xtest)

In [ ]:
# calculate the accuracy of the classifier's predictions on the test set.
y_test_pred_accuracy = accuracy_score(ytest, y_test_pred)
y_test_pred_accuracy

0.821

In [ ]:
# classification report for the validation set
print(classification_report(y_valid, y_valid_pred))

              precision    recall  f1-score   support

           0       0.81      0.78      0.79      7481
           1       0.84      0.76      0.80      7955
           2       0.84      0.88      0.86      8252
           3       0.78      0.78      0.78      8075
           4       0.84      0.89      0.86      8237

    accuracy                           0.82     40000
   macro avg       0.82      0.82      0.82     40000
weighted avg       0.82      0.82      0.82     40000



In [ ]:
# confusion matrix for the validation set
print(confusion_matrix(y_valid, y_valid_pred))

[[5830  574  477  512   88]
 [ 762 6077  589  377  150]
 [ 229  330 7242  242  209]
 [ 351  191  201 6333  999]
 [  57   72  148  608 7352]]


In [ ]:
# classification report for the test set
print(classification_report(ytest, y_test_pred))

              precision    recall  f1-score   support

           0       0.82      0.77      0.79      1873
           1       0.84      0.77      0.80      2086
           2       0.83      0.89      0.86      1997
           3       0.78      0.78      0.78      2019
           4       0.83      0.89      0.86      2025

    accuracy                           0.82     10000
   macro avg       0.82      0.82      0.82     10000
weighted avg       0.82      0.82      0.82     10000



In [ ]:
# confusion matrix for the test set
print(confusion_matrix(ytest, y_test_pred))

[[1446  172  118  119   18]
 [ 184 1604  144  114   40]
 [  44   63 1772   62   56]
 [  78   54   53 1576  258]
 [  14   16   37  146 1812]]


#### Random Forest

In [ ]:
from sklearn.pipeline import make_pipeline
# Training the model
rf_classifier = make_pipeline(TfidfVectorizer(), RandomForestClassifier(max_depth=20))
rf_classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('randomforestclassifier',
                 RandomForestClassifier(max_depth=20))])

In [ ]:
#To make predictions on the validation set.
y_valid_pred = rf_classifier.predict(X_valid)

In [ ]:
# calculate the accuracy of the classifier's predictions on the validation set.
y_valid_pred_accuracy = accuracy_score(y_valid, y_valid_pred)
y_valid_pred_accuracy

0.809425

In [ ]:
# Make predictions on the test set.
y_test_pred = rf_classifier.predict(Xtest)

In [ ]:
# calculate the accuracy of the classifier's predictions on the test set.
y_test_pred_accuracy = accuracy_score(ytest, y_test_pred)
y_test_pred_accuracy

0.8097

In [ ]:
# classification report for the validation set
print(classification_report(y_valid, y_valid_pred))

              precision    recall  f1-score   support

           0       0.81      0.79      0.80      7481
           1       0.77      0.79      0.78      7955
           2       0.84      0.85      0.84      8252
           3       0.82      0.74      0.78      8075
           4       0.81      0.88      0.85      8237

    accuracy                           0.81     40000
   macro avg       0.81      0.81      0.81     40000
weighted avg       0.81      0.81      0.81     40000



In [ ]:
# confusion matrix for the validation set
print(confusion_matrix(y_valid, y_valid_pred))

[[5891  738  422  327  103]
 [ 649 6271  568  289  178]
 [ 276  509 6984  171  312]
 [ 388  398  229 5947 1113]
 [  79  240  137  497 7284]]


In [ ]:
# classification report for the test set
print(classification_report(ytest, y_test_pred))

              precision    recall  f1-score   support

           0       0.83      0.77      0.80      1873
           1       0.78      0.80      0.79      2086
           2       0.83      0.85      0.84      1997
           3       0.82      0.73      0.77      2019
           4       0.80      0.89      0.84      2025

    accuracy                           0.81     10000
   macro avg       0.81      0.81      0.81     10000
weighted avg       0.81      0.81      0.81     10000



In [ ]:
# confusion matrix for the test set
print(confusion_matrix(ytest, y_test_pred))

[[1444  218  109   76   26]
 [ 138 1666  147   86   49]
 [  59  123 1700   44   71]
 [  89   91   57 1476  306]
 [  15   49   37  113 1811]]


#### Decision Tree

In [ ]:
from sklearn.pipeline import make_pipeline
# Training the model
dtree_classifier = make_pipeline(TfidfVectorizer(), DecisionTreeClassifier(max_depth=20))
dtree_classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('decisiontreeclassifier',
                 DecisionTreeClassifier(max_depth=20))])

In [ ]:
#To make predictions on the validation set.
y_valid_pred = dtree_classifier.predict(X_valid)

In [ ]:
# calculate the accuracy of the classifier's predictions on the validation set.
y_valid_pred_accuracy = accuracy_score(y_valid, y_valid_pred)
y_valid_pred_accuracy

0.75095

In [ ]:
# Make predictions on the test set.
y_test_pred = dtree_classifier.predict(Xtest)

In [ ]:
# calculate the accuracy of the classifier's predictions on the test set.
y_test_pred_accuracy = accuracy_score(ytest, y_test_pred)
y_test_pred_accuracy

0.7551

In [ ]:
# classification report for the validation set
print(classification_report(y_valid, y_valid_pred))

              precision    recall  f1-score   support

           0       0.78      0.72      0.75      7481
           1       0.64      0.76      0.70      7955
           2       0.83      0.77      0.80      8252
           3       0.76      0.72      0.74      8075
           4       0.77      0.79      0.78      8237

    accuracy                           0.75     40000
   macro avg       0.76      0.75      0.75     40000
weighted avg       0.76      0.75      0.75     40000



In [ ]:
# confusion matrix for the validation set
print(confusion_matrix(y_valid, y_valid_pred))

[[5372 1104  383  408  214]
 [ 672 6049  490  392  352]
 [ 350  863 6345  288  406]
 [ 343  778  187 5804  963]
 [ 118  612  274  765 6468]]


In [ ]:
# classification report for the test set
print(classification_report(ytest, y_test_pred))

              precision    recall  f1-score   support

           0       0.80      0.70      0.74      1873
           1       0.65      0.76      0.70      2086
           2       0.83      0.79      0.81      1997
           3       0.76      0.73      0.74      2019
           4       0.77      0.80      0.79      2025

    accuracy                           0.76     10000
   macro avg       0.76      0.75      0.76     10000
weighted avg       0.76      0.76      0.76     10000



In [ ]:
# confusion matrix for the test set
print(confusion_matrix(ytest, y_test_pred))

[[1310  306   99  110   48]
 [ 172 1581  132  115   86]
 [  63  197 1571   70   96]
 [  87  178   40 1470  244]
 [  12  162   58  174 1619]]
